### ISSUE TITLE
Use the TZDIR environment variable to find the system db?

### ISSUE THREAD

**Issue by danderson** [smartrent/zoneinfo#34]
zoneinfo currently looks at the TZPATH, which doesn't seem to be a standard environment variable for the zoneinfo path. The only reference I could find to TZPATH is in python's zoneinfo module, where it's a package variable not an environment variable (although it can initialize itself from the PYTHONTZPATH envvar).

TZDIR seems to be specified in Posix as the environment variable that points to an alternate timezone database. Notably, glibc respects TZDIR, and NixOS uses TZDIR to point to /etc/zoneinfo.

Should `Zoneinfo.tzpath/0` look at TZDIR as well as TZPATH? That would make zoneinfo work gracefully on systems using the glibc-flavored override.

**Comment by fhunleth** [comment]
Thanks for reporting this. I don't remember the history of `TZPATH`, but I agree that it would be better to use the standard environment variable. 

Does #36 work for you?

**Comment by danderson** [comment]
Yup, that looks good. Thank you!
